### ISSUE TITLE
Dockerfile directory issue 

### ISSUE THREAD

**Issue by ashrafuzzamanabir** [ashrafuzzamanabir/book_cycle_django#5]
please check github actions  test,test100 and test111 . there is a no directory found error if we don't copy requirements.txt from src to app it will run in github actions.  but when we  copy it then there is a new problem arise. the file does not build in local my pc,  

my directory 
project-root/
         |-- src/
         |   |-- Dockerfile
         |   |-- requirements.txt
         |-- docker-compose.yml

 
![Screenshot 2023-11-19 033632](https://github.com/ashrafuzzamanabir/book_cycle_django/assets/62021530/1086dbcb-c5df-4b86-a49b-cde586dd1abb)

COPY src/requirements.txt /app/
if this is in github action then it run and push
![Screenshot 2023-11-19 035529](https://github.com/ashrafuzzamanabir/book_cycle_django/assets/62021530/7c6c813e-2c43-4e7d-81ac-57eabb09b124)

 
![Screenshot 2023-11-19 034052](https://github.com/ashrafuzzamanabir/book_cycle_django/assets/62021530/ddf36b6c-fe21-4d23-93ac-f651e22ee2d2)

another reverse thing 
 
![Screenshot 2023-11-19 034438](https://github.com/ashrafuzzamanabir/book_cycle_django/assets/62021530/2cad8826-7e0a-4172-be2a-d200c3f076e6)
![Screenshot 2023-11-19 034535](https://github.com/ashrafuzzamanabir/book_cycle_django/assets/62021530/a5ac8e1c-1d92-41df-864c-c8e253507765)
__

**Comment by moonstruck** [comment]
I've created a pull request to fix this issue.
https://github.com/ashrafuzzamanabir/book_cycle_django/pull/8

**Comment by ashrafuzzamanabir** [comment]
Thank You  Vhai @moonstruck  for solving the issue..
